name: "Dockerfile build"
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build Docker image"
      run: docker build .
